// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cargos.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLegs = `-- name: DeleteLegs :exec
DELETE FROM legs WHERE cargo_id = $1
`

func (q *Queries) DeleteLegs(ctx context.Context, cargoID string) error {
	_, err := q.db.Exec(ctx, deleteLegs, cargoID)
	return err
}

const findAllCargos = `-- name: FindAllCargos :many
SELECT tracking_id, origin, spec_origin, spec_destination, spec_deadline,
       transport_status, routing_status, misdirected, eta,
       next_activity_type, next_activity_location, next_activity_voyage,
       last_location, current_voyage, unloaded_at_dest,
       last_event_type, last_event_cargo, last_event_voyage,
       last_event_location, last_event_completion, last_event_registration,
       calculated_at
FROM cargos ORDER BY tracking_id
`

func (q *Queries) FindAllCargos(ctx context.Context) ([]Cargo, error) {
	rows, err := q.db.Query(ctx, findAllCargos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cargo{}
	for rows.Next() {
		var i Cargo
		if err := rows.Scan(
			&i.TrackingID,
			&i.Origin,
			&i.SpecOrigin,
			&i.SpecDestination,
			&i.SpecDeadline,
			&i.TransportStatus,
			&i.RoutingStatus,
			&i.Misdirected,
			&i.Eta,
			&i.NextActivityType,
			&i.NextActivityLocation,
			&i.NextActivityVoyage,
			&i.LastLocation,
			&i.CurrentVoyage,
			&i.UnloadedAtDest,
			&i.LastEventType,
			&i.LastEventCargo,
			&i.LastEventVoyage,
			&i.LastEventLocation,
			&i.LastEventCompletion,
			&i.LastEventRegistration,
			&i.CalculatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCargo = `-- name: FindCargo :one
SELECT tracking_id, origin, spec_origin, spec_destination, spec_deadline,
       transport_status, routing_status, misdirected, eta,
       next_activity_type, next_activity_location, next_activity_voyage,
       last_location, current_voyage, unloaded_at_dest,
       last_event_type, last_event_cargo, last_event_voyage,
       last_event_location, last_event_completion, last_event_registration,
       calculated_at
FROM cargos WHERE tracking_id = $1
`

func (q *Queries) FindCargo(ctx context.Context, trackingID string) (Cargo, error) {
	row := q.db.QueryRow(ctx, findCargo, trackingID)
	var i Cargo
	err := row.Scan(
		&i.TrackingID,
		&i.Origin,
		&i.SpecOrigin,
		&i.SpecDestination,
		&i.SpecDeadline,
		&i.TransportStatus,
		&i.RoutingStatus,
		&i.Misdirected,
		&i.Eta,
		&i.NextActivityType,
		&i.NextActivityLocation,
		&i.NextActivityVoyage,
		&i.LastLocation,
		&i.CurrentVoyage,
		&i.UnloadedAtDest,
		&i.LastEventType,
		&i.LastEventCargo,
		&i.LastEventVoyage,
		&i.LastEventLocation,
		&i.LastEventCompletion,
		&i.LastEventRegistration,
		&i.CalculatedAt,
	)
	return i, err
}

const findLegs = `-- name: FindLegs :many
SELECT voyage_number, load_location, unload_location, load_time, unload_time
FROM legs WHERE cargo_id = $1 ORDER BY seq
`

type FindLegsRow struct {
	VoyageNumber   string
	LoadLocation   string
	UnloadLocation string
	LoadTime       pgtype.Timestamptz
	UnloadTime     pgtype.Timestamptz
}

func (q *Queries) FindLegs(ctx context.Context, cargoID string) ([]FindLegsRow, error) {
	rows, err := q.db.Query(ctx, findLegs, cargoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindLegsRow{}
	for rows.Next() {
		var i FindLegsRow
		if err := rows.Scan(
			&i.VoyageNumber,
			&i.LoadLocation,
			&i.UnloadLocation,
			&i.LoadTime,
			&i.UnloadTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLeg = `-- name: InsertLeg :exec
INSERT INTO legs (cargo_id, voyage_number, load_location, unload_location, load_time, unload_time, seq)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertLegParams struct {
	CargoID        string
	VoyageNumber   string
	LoadLocation   string
	UnloadLocation string
	LoadTime       pgtype.Timestamptz
	UnloadTime     pgtype.Timestamptz
	Seq            int32
}

func (q *Queries) InsertLeg(ctx context.Context, arg InsertLegParams) error {
	_, err := q.db.Exec(ctx, insertLeg,
		arg.CargoID,
		arg.VoyageNumber,
		arg.LoadLocation,
		arg.UnloadLocation,
		arg.LoadTime,
		arg.UnloadTime,
		arg.Seq,
	)
	return err
}

const upsertCargo = `-- name: UpsertCargo :exec
INSERT INTO cargos (
    tracking_id, origin, spec_origin, spec_destination, spec_deadline,
    transport_status, routing_status, misdirected, eta,
    next_activity_type, next_activity_location, next_activity_voyage,
    last_location, current_voyage, unloaded_at_dest,
    last_event_type, last_event_cargo, last_event_voyage,
    last_event_location, last_event_completion, last_event_registration,
    calculated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22)
ON CONFLICT (tracking_id) DO UPDATE SET
    origin = EXCLUDED.origin,
    spec_origin = EXCLUDED.spec_origin,
    spec_destination = EXCLUDED.spec_destination,
    spec_deadline = EXCLUDED.spec_deadline,
    transport_status = EXCLUDED.transport_status,
    routing_status = EXCLUDED.routing_status,
    misdirected = EXCLUDED.misdirected,
    eta = EXCLUDED.eta,
    next_activity_type = EXCLUDED.next_activity_type,
    next_activity_location = EXCLUDED.next_activity_location,
    next_activity_voyage = EXCLUDED.next_activity_voyage,
    last_location = EXCLUDED.last_location,
    current_voyage = EXCLUDED.current_voyage,
    unloaded_at_dest = EXCLUDED.unloaded_at_dest,
    last_event_type = EXCLUDED.last_event_type,
    last_event_cargo = EXCLUDED.last_event_cargo,
    last_event_voyage = EXCLUDED.last_event_voyage,
    last_event_location = EXCLUDED.last_event_location,
    last_event_completion = EXCLUDED.last_event_completion,
    last_event_registration = EXCLUDED.last_event_registration,
    calculated_at = EXCLUDED.calculated_at
`

type UpsertCargoParams struct {
	TrackingID            string
	Origin                string
	SpecOrigin            string
	SpecDestination       string
	SpecDeadline          pgtype.Timestamptz
	TransportStatus       int32
	RoutingStatus         int32
	Misdirected           bool
	Eta                   pgtype.Timestamptz
	NextActivityType      pgtype.Int4
	NextActivityLocation  pgtype.Text
	NextActivityVoyage    pgtype.Text
	LastLocation          pgtype.Text
	CurrentVoyage         pgtype.Text
	UnloadedAtDest        bool
	LastEventType         pgtype.Int4
	LastEventCargo        pgtype.Text
	LastEventVoyage       pgtype.Text
	LastEventLocation     pgtype.Text
	LastEventCompletion   pgtype.Timestamptz
	LastEventRegistration pgtype.Timestamptz
	CalculatedAt          pgtype.Timestamptz
}

func (q *Queries) UpsertCargo(ctx context.Context, arg UpsertCargoParams) error {
	_, err := q.db.Exec(ctx, upsertCargo,
		arg.TrackingID,
		arg.Origin,
		arg.SpecOrigin,
		arg.SpecDestination,
		arg.SpecDeadline,
		arg.TransportStatus,
		arg.RoutingStatus,
		arg.Misdirected,
		arg.Eta,
		arg.NextActivityType,
		arg.NextActivityLocation,
		arg.NextActivityVoyage,
		arg.LastLocation,
		arg.CurrentVoyage,
		arg.UnloadedAtDest,
		arg.LastEventType,
		arg.LastEventCargo,
		arg.LastEventVoyage,
		arg.LastEventLocation,
		arg.LastEventCompletion,
		arg.LastEventRegistration,
		arg.CalculatedAt,
	)
	return err
}
