// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: handling_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findHandlingEventsByCargo = `-- name: FindHandlingEventsByCargo :many
SELECT type, cargo_id, voyage_number, location, completion_time, registration_time
FROM handling_events WHERE cargo_id = $1 ORDER BY completion_time
`

type FindHandlingEventsByCargoRow struct {
	Type             int32
	CargoID          string
	VoyageNumber     string
	Location         string
	CompletionTime   pgtype.Timestamptz
	RegistrationTime pgtype.Timestamptz
}

func (q *Queries) FindHandlingEventsByCargo(ctx context.Context, cargoID string) ([]FindHandlingEventsByCargoRow, error) {
	rows, err := q.db.Query(ctx, findHandlingEventsByCargo, cargoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindHandlingEventsByCargoRow{}
	for rows.Next() {
		var i FindHandlingEventsByCargoRow
		if err := rows.Scan(
			&i.Type,
			&i.CargoID,
			&i.VoyageNumber,
			&i.Location,
			&i.CompletionTime,
			&i.RegistrationTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHandlingEvent = `-- name: InsertHandlingEvent :exec
INSERT INTO handling_events (type, cargo_id, voyage_number, location, completion_time, registration_time)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertHandlingEventParams struct {
	Type             int32
	CargoID          string
	VoyageNumber     string
	Location         string
	CompletionTime   pgtype.Timestamptz
	RegistrationTime pgtype.Timestamptz
}

func (q *Queries) InsertHandlingEvent(ctx context.Context, arg InsertHandlingEventParams) error {
	_, err := q.db.Exec(ctx, insertHandlingEvent,
		arg.Type,
		arg.CargoID,
		arg.VoyageNumber,
		arg.Location,
		arg.CompletionTime,
		arg.RegistrationTime,
	)
	return err
}
