// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: locations.sql

package sqlcgen

import (
	"context"
)

const findAllLocations = `-- name: FindAllLocations :many
SELECT unlocode, name FROM locations ORDER BY unlocode
`

func (q *Queries) FindAllLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, findAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Location{}
	for rows.Next() {
		var i Location
		if err := rows.Scan(&i.Unlocode, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findLocation = `-- name: FindLocation :one
SELECT unlocode, name FROM locations WHERE unlocode = $1
`

func (q *Queries) FindLocation(ctx context.Context, unlocode string) (Location, error) {
	row := q.db.QueryRow(ctx, findLocation, unlocode)
	var i Location
	err := row.Scan(&i.Unlocode, &i.Name)
	return i, err
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT INTO locations (unlocode, name) VALUES ($1, $2)
ON CONFLICT (unlocode) DO UPDATE SET name = EXCLUDED.name
`

type UpsertLocationParams struct {
	Unlocode string
	Name     string
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.Exec(ctx, upsertLocation, arg.Unlocode, arg.Name)
	return err
}
