// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cargo struct {
	TrackingID            string
	Origin                string
	SpecOrigin            string
	SpecDestination       string
	SpecDeadline          pgtype.Timestamptz
	TransportStatus       int32
	RoutingStatus         int32
	Misdirected           bool
	Eta                   pgtype.Timestamptz
	NextActivityType      pgtype.Int4
	NextActivityLocation  pgtype.Text
	NextActivityVoyage    pgtype.Text
	LastLocation          pgtype.Text
	CurrentVoyage         pgtype.Text
	UnloadedAtDest        bool
	LastEventType         pgtype.Int4
	LastEventCargo        pgtype.Text
	LastEventVoyage       pgtype.Text
	LastEventLocation     pgtype.Text
	LastEventCompletion   pgtype.Timestamptz
	LastEventRegistration pgtype.Timestamptz
	CalculatedAt          pgtype.Timestamptz
}

type CarrierMovement struct {
	ID                int32
	VoyageNumber      string
	DepartureLocation string
	ArrivalLocation   string
	DepartureTime     pgtype.Timestamptz
	ArrivalTime       pgtype.Timestamptz
	Seq               int32
}

type HandlingEvent struct {
	ID               int32
	Type             int32
	CargoID          string
	VoyageNumber     string
	Location         string
	CompletionTime   pgtype.Timestamptz
	RegistrationTime pgtype.Timestamptz
}

type Leg struct {
	ID             int32
	CargoID        string
	VoyageNumber   string
	LoadLocation   string
	UnloadLocation string
	LoadTime       pgtype.Timestamptz
	UnloadTime     pgtype.Timestamptz
	Seq            int32
}

type Location struct {
	Unlocode string
	Name     string
}

type Voyage struct {
	Number string
}
