// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voyages.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCarrierMovements = `-- name: DeleteCarrierMovements :exec
DELETE FROM carrier_movements WHERE voyage_number = $1
`

func (q *Queries) DeleteCarrierMovements(ctx context.Context, voyageNumber string) error {
	_, err := q.db.Exec(ctx, deleteCarrierMovements, voyageNumber)
	return err
}

const findCarrierMovements = `-- name: FindCarrierMovements :many
SELECT departure_location, arrival_location, departure_time, arrival_time
FROM carrier_movements WHERE voyage_number = $1 ORDER BY seq
`

type FindCarrierMovementsRow struct {
	DepartureLocation string
	ArrivalLocation   string
	DepartureTime     pgtype.Timestamptz
	ArrivalTime       pgtype.Timestamptz
}

func (q *Queries) FindCarrierMovements(ctx context.Context, voyageNumber string) ([]FindCarrierMovementsRow, error) {
	rows, err := q.db.Query(ctx, findCarrierMovements, voyageNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindCarrierMovementsRow{}
	for rows.Next() {
		var i FindCarrierMovementsRow
		if err := rows.Scan(
			&i.DepartureLocation,
			&i.ArrivalLocation,
			&i.DepartureTime,
			&i.ArrivalTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findVoyage = `-- name: FindVoyage :one
SELECT number FROM voyages WHERE number = $1
`

func (q *Queries) FindVoyage(ctx context.Context, number string) (string, error) {
	row := q.db.QueryRow(ctx, findVoyage, number)
	err := row.Scan(&number)
	return number, err
}

const insertCarrierMovement = `-- name: InsertCarrierMovement :exec
INSERT INTO carrier_movements
    (voyage_number, departure_location, arrival_location, departure_time, arrival_time, seq)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertCarrierMovementParams struct {
	VoyageNumber      string
	DepartureLocation string
	ArrivalLocation   string
	DepartureTime     pgtype.Timestamptz
	ArrivalTime       pgtype.Timestamptz
	Seq               int32
}

func (q *Queries) InsertCarrierMovement(ctx context.Context, arg InsertCarrierMovementParams) error {
	_, err := q.db.Exec(ctx, insertCarrierMovement,
		arg.VoyageNumber,
		arg.DepartureLocation,
		arg.ArrivalLocation,
		arg.DepartureTime,
		arg.ArrivalTime,
		arg.Seq,
	)
	return err
}

const upsertVoyage = `-- name: UpsertVoyage :exec
INSERT INTO voyages (number) VALUES ($1) ON CONFLICT (number) DO NOTHING
`

func (q *Queries) UpsertVoyage(ctx context.Context, number string) error {
	_, err := q.db.Exec(ctx, upsertVoyage, number)
	return err
}
